### ISSUE TITLE
Relicense to GPLv2 or later

### ISSUE THREAD

**Issue by zerodogg** [steamtricks/steamtricks-data#2]
I'm the author of [steam-linux-workarounds](https://github.com/zerodogg/steam-linux-workarounds), a project with a similar, though not identical, goal to that of steamtricks. Right now we're using incompatible licenses. You with GPLv2 only, me with GPLv3 or later. I suggest a compromise. You relicense your -data repo to GPLv2 or later (keeping steamtricks itself GPLv2 only), I'll relicense the actual patches in steam-linux-workarounds to GPLv2 or later (keeping the rest GPLv3 or later). Thus we could exchange, adapt and reuse each others fixes without needing rewrites (and tbh., some of the fixes would probably result in identical changes being made anyway).

**Comment by boombatower** [comment]
Sorry for slow response.

I am not opposed to reliscensing the `steamtricks-data` repo, but I'd like to get an idea of how you envision the fixes being shared. Using them direct from eachother's repos or reworking them into our own formats?

I see https://github.com/zerodogg/steam-linux-workarounds/blob/master/patches/Evoland.sh#L20 is downloading flashplayer. My thought was any missing system dependencies should be provided as proper packages and a steamtricks repo for the particular distro. Since I am using the Open Build Service which makes it easy to ship for all major distros it seemed far cleaner then re-implementing installation of such things missing all the security and management features of package managers. For example the undo portion would be built-in if flash payer was installed as a proper package. Any other game file changes can be undone by verifying game files via Steam. As such the only changes made by steamtricks are to patch/remove steam/game related files or trigger system package installation.

Additionally, steamtricks supports fixes specific to game revision which is relevant for some games that intentionally allow people to play older versions.

**Comment by zerodogg** [comment]
My thought is to rework them into a format suiting the project. As you point out, we differ quite a bit in our approaches. steam-linux-workarounds offers one-off scripts that run as the user that uses Steam, while your project offers a much more integrated (and possibly cleaner) approach. This is why I think that there might be a benifit to both projects - to different users. But, given that the solutions are often the same, but with differing implementations, my thought is that it is probably a lot easier to just adapt from each other, instead of rewriting it alltogether. I could see myself submitting pull requests to steamtricks-data for changes that are simple enough, and notifying you about others (such as the Evoland one, which would require more than a quick patch). And, for instance, I could probably copy the AndYetItMoves patch almost wholesale into steam-linux-workarounds.

In the Evoland case, it downloads flash player, yes, but it installs it locally to the game, so it's not available to be used outside it. steam-linux-workarounds won't make systemwide (or user-wide) changes.

**Comment by boombatower** [comment]
Sounds good. I'll go ahead and change licensing and look at your existing fixes. I have a couple games on my backlog that I need to get back to, but hoping to get others involved since I do not own all games. ;) Happy to see others wanting to automate this mess.

Also note that steamtricks is currently part of default Steam package in openSUSE Tumbleweed (finally). I am hopeful that will result in some more eyes, but we will see.

**Comment by zerodogg** [comment]
I suggest the following patch

```patch
From 3bf6ff0625dd9844a56fe5e331523cb3b72d44d2 Mon Sep 17 00:00:00 2001
From: Eskild Hustvedt <code@zerodogg.org>
Date: Fri, 10 Feb 2017 10:12:19 +0100
Subject: [PATCH] Relicense to "or later"

---
 COPYING | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/COPYING b/COPYING
index 5c63403..47f7f3c 100644
--- a/COPYING
+++ b/COPYING
@@ -1,6 +1,6 @@
-Note that the only valid version of the GPL as far as the steamtricks
-is concerned is _this_ particular version of the license (ie v2, not
-v2.2 or v3.x or whatever), unless explicitly otherwise stated.
+The steamtricks-data repository is licensed under under the terms of the GNU
+General Public License as published by the Free Software Foundation; either
+version 2 of the License, or (at your option) any later version.
 
 ----------------------------------------
 
-- 
2.11.1```

**Comment by moozaad** [comment]
" under under"

**Comment by zerodogg** [comment]
Right, without the double under.

I'm not submitting this explicitly as a pull request as I can't relicense someone elses code, and a pull request would require me pushing the change.

**Comment by zerodogg** [comment]
I've also relicensed the patches in steam-linux-workarounds under GPLv2+ now: https://github.com/zerodogg/steam-linux-workarounds/commit/e18790d18fad901fc9cdcabd154122cc1b25295e

**Comment by boombatower** [comment]
Presumably I can just drop the preamble and it will apply as normal.

**Comment by boombatower** [comment]
6112c7a2c7943eda249c4637ffffad073bccbfae
